site_name: EAR Handbook
site_url: https://handbook.ecosystemaction.com
theme:
  name: material
#  features:
#    - navigation.expand
nav:
  - Introduction: index.md
  - Table of contents: contents.md
  - Work with EAR: work-with-ear.md
  - Support EAR: support-ear.md
  - Glossary: glossary.md
  - Agreements:
    - EAR agreements: agreements/index.md
    - Charter: agreements/charter.md
    - Decisions:
      - EAR decisions: agreements/decisions/index.md
      - Types of decisions: agreements/decisions/decision-types.md
      - Decision-making templates: agreements/decisions/decision-templates.md
    - Project committee: agreements/project-committee.md
    - Personal conduct: agreements/personal-conduct.md
    - Membership: agreements/membership.md
    - Research & innovation: 
      - EAR Research & innovation: agreements/research-imagination/index.md
      - Research principles: agreements/research-imagination/research-principles.md
      - Data synthesis principles: agreements/research-imagination/data-synthesis-principles.md
    - Operating model: agreements/operating-model.md
    - Member services:
      - EAR member services: agreements/internal-services/index.md
      - Care: agreements/internal-services/care.md
      - Commons: agreements/internal-services/commons.md
      - Convening: agreements/internal-services/convening.md
      - Craft: agreements/internal-services/craft.md
      - Editorial: agreements/internal-services/editorial.md
      - Discovery: agreements/internal-services/discovery.md
      - Financial development: agreements/internal-services/development.md
      - Software systems: agreements/internal-services/software-systems.md
    - Steering: agreements/steering.md
    - Financial development: agreements/financial.md
    - Meetings & events: agreements/meetings-events.md
    - Communications: agreements/communications.md
    - Software systems: agreements/software-systems.md
  - Guides:
    - EAR guides: guides/index.md
    - How we show up: guides/how-we-show-up.md
    - Internal coordination: guides/internal-coordination.md
    - Schedule a meeting or event: guides/schedule.md
    - External communications: guides/public-relations.md
    - Conflict resolution: guides/conflict-resolution.md
    - Opportunities: guides/opportunities.md
    - Research projects: guides/research-projects.md
    - Action research methods: guides/action-research-methods.md
    - Request financial support: guides/request-financial-support.md
    - Contribute to the handbook:
      - How to contribute: guides/contribute/index.md
      - MKDocs: guides/contribute/mkdocs.md